// Generates a full verbs.js dataset (matches the schema used by verbs.js in the quiz app)
// from the conjugation-fr package (Verbiste-derived, ~7000 French verbs).
//
// Usage:
//   npm install conjugation-fr
//   node generate-verbs.js > verbs-master.js
//
// Output: const WERKWOORDEN = { ...alle 7000+ werkwoorden... };

const fs = require("fs");
const path = require("path");
const conjugationFR = require("conjugation-fr");

// Full verb -> {template, auxiliary} list shipped inside conjugation-fr.
const verbsFrPath = require.resolve("conjugation-fr/verbs-fr.json");
const alleWerkwoorden = JSON.parse(fs.readFileSync(verbsFrPath, "utf8"));

// Maps our tense ids (used in verbs.js / TIJDEN) to conjugation-fr's [mode, tense] pair.
// "futur-proche" is deliberately absent here: it's periphrastic (aller + infinitive),
// computed live in the app instead of stored per verb.
const TIJD_MAPPING = {
  "indicatif-present": ["indicative", "present"],
  "indicatif-imparfait": ["indicative", "imperfect"],
  "indicatif-futur": ["indicative", "future"],
  "indicatif-passe-compose": ["indicative", "perfect-tense"],
  "conditionnel-present": ["conditional", "present"],
  "subjonctif-present": ["subjunctive", "present"],
  "imperatif-present": ["imperative", "imperative-present"]
};

// Imperative only exists for tu/nous/vous (indices 1,3,4) — expect fewer forms for that tense.
function verwachteLengte(onsTijdId) {
  return onsTijdId === "imperatif-present" ? 3 : 6;
}

// Rough pedagogical group classification (not used by the app logic itself,
// kept as metadata only). 1 = regular -er, 2 = regular -ir with -iss- infix, 3 = rest.
function bepaalGroep(infinitief, presentVormen) {
  if (infinitief.endsWith("er") && infinitief !== "aller") return 1;
  if (infinitief.endsWith("ir") && presentVormen[3] && presentVormen[3].endsWith("issons")) return 2;
  return 3;
}

const resultaat = {};
const overgeslagen = []; // verbs where one or more tenses failed to conjugate (defective verbs, etc.)

for (const infinitief of Object.keys(alleWerkwoorden)) {
  const { aux } = alleWerkwoorden[infinitief];
  const entry = { hulpwerkwoord: aux === "être" ? "être" : "avoir" };
  let mislukt = false;
  let presentVormen = null;

  for (const [onsTijdId, [mode, tense]] of Object.entries(TIJD_MAPPING)) {
    try {
      const vormen = conjugationFR.conjugate(infinitief, mode, tense);
      if (!vormen || vormen.length < verwachteLengte(onsTijdId)) {
        mislukt = true;
        continue;
      }
      // Build a fixed 6-slot array [je,tu,il,nous,vous,ils], leaving unsupported
      // persons (e.g. je/il/ils for the imperative) as null instead of guessing.
      const rij = [null, null, null, null, null, null];
      vormen.forEach(v => { if (v.verb) rij[v.pronounIndex] = v.verb; });
      entry[onsTijdId] = rij;
      if (onsTijdId === "indicatif-present") presentVormen = rij;
    } catch (e) {
      mislukt = true;
    }
  }

  entry.groep = bepaalGroep(infinitief, presentVormen || []);
  resultaat[infinitief] = entry;
  if (mislukt) overgeslagen.push(infinitief);
}

const output = `// Auto-generated by generate-verbs.js from conjugation-fr (Verbiste data).
// ${Object.keys(resultaat).length} verbs. Regenerate any time the source package updates.
// Pronoun order per tense array: [je, tu, il, nous, vous, ils]
const WERKWOORDEN = ${JSON.stringify(resultaat, null, 1)};
`;

fs.writeFileSync(path.join(__dirname, "verbs-master.js"), output, "utf8");

console.error(`Done. ${Object.keys(resultaat).length} verbs written to verbs-master.js`);
if (overgeslagen.length) {
  console.error(`${overgeslagen.length} verbs had at least one incomplete tense (defective verbs, e.g. weather verbs): see skipped.txt`);
  fs.writeFileSync(path.join(__dirname, "skipped.txt"), overgeslagen.join("\n"), "utf8");
}
